brew cask install alfred
brew cask install atom
brew cask install bettertouchtool
brew cask install colorpicker-skalacolor
brew cask install cycling74-max
brew cask install daisydisk
brew cask install dropbox
brew cask install firefox
brew cask install flux
brew cask install github-desktop
brew cask install google-nik-collection
brew cask install google-photos-backup
brew cask install handbrake
brew cask install iterm2
brew cask install java
brew cask install karabiner
brew cask install onyx
brew cask install parallels-desktop
brew cask install processing
brew cask install sketch
brew cask install sourcetree
brew cask install xld
